# Generated by Django 4.2 on 2024-08-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0015_alter_logentry_changes'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeTrackingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=400)),
                ('log_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auditlog.logentry')),
            ],
        ),
    ]
